# Generated by Django 2.2 on 2020-08-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
